#!/usr/bin/env bash
# configure new Ubuntu machine using a bash script
# install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# setup custom HTML file
sudo cat <<- _EOF_ > /var/www/html/index.html
     Hello World!
_EOF_

# config Nginx to listen on port 80
sudo cat <<- _EOF_ > /etc/nginx/sites_available/default
	server {
		location / {
			root /var/www/html;
			index.html;
		}
	}
_EOF_

# start Nginx
sudo service nginx start
