#!/usr/bin/env bash 
#write a bash script that configures a new ubuntu machine
#respect When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!

sudo apt-get -y update
sudo apt-get -y install ngingx
ufw allow 'Ngingx HTTP'
echo 'Hello World!' > /var/www/html/index.html
sudo service ngingx start
