#!/usr/bin/env bash
#configure your Nginx server to have a cutom 404 page that contains Ceci n'est pas une page.
#the page must return HTTP 404 error.

sudo apt-get update
sudo apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

echo "server {
   listen 80;
   listen [::]:80 default_server;
   root  /etc/nginx/html;
   index index.html index.htm;
   location  /redirect_me {
	return 301 http://cuberule.com/;
   }
   error_page 404 /404.html;
   location /404 {
     root /etc/nginx/html;
     internal;
   }
}" > /etc/nginx/sites-available/default

service nginx restart

