#!/usr/bin/env bash
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed (refer to the example)

for file in *; do
	if [[ $file =~ ^\. && -f $file ]]; then
		name_after_dash=$(echo "$file" | cut -d '-' -f 2-)
		echo "$name_after_dash"
	fi
done
