#!/usr/bin/env bash
#dipslays:
#The content of the current directory
#In a list format
#here only the part of the name after the first dash is displayed (refer to the example)

for f in *; do
	echo "$f" | cut -d '-' -f 2
done
