#!/usr/bin/env bash
# change localhost to 127.0.0.2
# change facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.02  localhost" >  ~/hosts.new
echo "8.8.8.8   facebook" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
