#!/usr/bin/env bash
# script that takes whoami as an argument for different users.

if [[ -z "$(getent passwd "$1")" ]]; then
    sudo useradd "$1" -p "$1"
    sudo -u "$1" whoami
    sudo userdel "$1"
else
    sudo -u "$1" whoami
fi