#!/usr/bin/env bash
# Script that configures a system to run nginx as nginx user 
chmod 666 /etc/nginx/nginx.conf
chown nginx /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-availble/default
pkill apache2
sudo -u nginx service nginx restart
